# Generated by Django 5.0.7 on 2024-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pop', models.PositiveBigIntegerField()),
                ('area', models.FloatField()),
                ('capitalcity', models.CharField(max_length=100)),
                ('flag', models.ImageField(upload_to='flag')),
                ('email', models.EmailField(max_length=254)),
                ('map', models.ImageField(upload_to='map')),
                ('website', models.URLField()),
            ],
        ),
    ]
